export const FETCH_CONTACT_INQUIRIES_REQUEST = "FETCH_CONTACT_INQUIRIES_REQUEST";
export const FETCH_CONTACT_INQUIRIES_SUCCESS = "FETCH_CONTACT_INQUIRIES_SUCCESS";
export const FETCH_CONTACT_INQUIRIES_FAILURE = "FETCH_CONTACT_INQUIRIES_FAILURE";
